services :
    postgres:
      image: postgres:latest
      container_name: postgres
      ports:
        - "5432:5432"
      environment:
        POSTGRES_USER: user
        POSTGRES_PASSWORD: data
        POSTGRES_DB: PGDB
      volumes:
        - ./init-db:/docker-entrypoint-initdb.d
        - pgdata:/var/lib/postgresql/data
        
      restart: unless-stopped
volumes:
  pgdata: 