services :
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: data
      POSTGRES_DB: PGDB
    volumes:
      - ./postgre-build:/docker-entrypoint-initdb.d
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - ollama-docker
    restart: unless-stopped
    
  ollama:
    container_name: ollama
    pull_policy: always
    image: ollama/ollama:latest
    tty: true
    ports:
      - 11434:11434
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all 
              capabilities: [gpu]
    environment:
      OLLAMA_KEEP_ALIVE: -1
    volumes:
      - ./ollama/ollama:/root/.ollama
      - ./ollama-build/init.sh:/init.sh
      - ./ollama-build/Modelfile:/Modelfile
    networks:
      - ollama-docker
    restart: always
    entrypoint: ["/usr/bin/bash", "/init.sh"]

  api:
    container_name : api
    build:
      dockerfile: ./api-build/Dockerfile
    environment:
      DB_USER: user
      DB_PASSWORD: data
      DB_NAME: PGDB
    ports:
      - 80:80
    volumes:
      - ./api:/app
      - ./data:/data
      - ./chroma-db:/chroma-db
    networks:
      - ollama-docker
    tty : true

    restart: always
    
  easy-dataset:
    image: ghcr.io/conardli/easy-dataset
    container_name: easy-dataset
    ports:
      - '1717:1717'
    volumes:
      - ./easy-dataset-db:/app/local-db
    restart: unless-stopped
    networks:
      - ollama-docker


networks:
  ollama-docker:
    driver: bridge